For this program, you will be coding some of the ideas around decision trees. In particular, you will be looking into splitting the root node for a tree. Data is provided via an input file. **Be sure to document your code.**

**You may not use an packages or "canned" code in your program other than simple function calls to needed math functions or file I/O**

The input file is a csv file named *DecTreeAssign1.dat* and is located in the Data folder on Google.

The first line contains the class name followed by the n feature names. Your program should allow any number of features >= 1. I.e., the number of features should not be hardcoded. Neither should the number of observations.

Each subsequent line is an observation that has the class indicator, "M" or "B", followed by numeric values for each of the n features.

Read the input file and build a data matrix such that the feature values are scaled in the interval [0, 1]. Calculate  the mean value for each feature after they are scaled.

You will now need to do some calculations for splitting the root node.

For the root node, print the following values to the console:
* Number of class "B" observations
* Number of class "M" observations
* Total number of observations
* Gini index for the root
* Entropy for the root

Here is an example console output:
```
Class B observations:   262
Class M observations:   198
Total observations:     460
Root gini:    0.4932
Root entropy: 0.9860
```

For each feature:

Calculate the Gini index and Entropy for each child node if a split is made on the mean value for the feature. Calculate the combined Gini index and Entropy for the child nodes. Child 1 is the < decision, and Child 2 is the >= decision.

Students should write their own Gini and Entropy functions.

Open a csv output file named: *DecTreeAssign1_out.csv*

Write one line to the output file for each feature that contains the following separated by commas:

* Feature name
* Feature mean value after scaling
* Child 1 count for class "B"
* Child 1 count for class "M"
* Child 1 Gini
* Child 1 Entropy
* Child 2 count for class "B"
* Child 2 count for class "M"
* Child 2 Gini
* Child 2 Entropy
* Combined Gini for Child 1 and Child 2
* Combined Entropy for Child 1 and Child 2

For readibility in my output file, all floats written were limited to 4 decimal places.

Here is an example of a possible first 4 lines of the output file (these are not necessarily what you will get, just an example).
```
F00, 0.3382,  311,   32, 0.1692, 0.7290,   46,  180, 0.3242, 0.7290, 0.2308, 0.5592
F01, 0.3240,  254,   52, 0.2821, 0.9658,  103,  160, 0.4765, 0.9658, 0.3720, 0.8001
F02, 0.3329,  313,   30, 0.1596, 0.7112,   44,  182, 0.3136, 0.7112, 0.2208, 0.5404
F03, 0.2169,  324,   41, 0.1994, 0.6385,   33,  171, 0.2712, 0.6385, 0.2252, 0.5541
```

Load the output file into Google Sheets, Excel or some other spreadsheet program. Determine which feature should be chosen to split on at the root using the combined Gini and Entropy criteria. Is it the same for both?

If you are interested, feel free to expand your program to do more. Be sure to document your code.

In [1]:
'''
Functions and imports for Decision Tree Assignment #1
'''

import  math
import numpy as np
import pandas as pd

In [2]:
'''
Decision Tree Assignment #1
'''

if __name__ == "__main__":
  #Data file name
  data_file_name = "INPUT FILE NAME GOES HERE"

In [3]:
data = pd.read_csv("/Users/Jerry/Desktop/CSC373/jupyter notebook/DecTreeAssign1.dat")
data

,Class,F00,F01,F02,F03,F04,F05,F06,F07,F08,...,F20,F21,F22,F23,F24,F25,F26,F27,F28,F29
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [4]:
data["F01"].min()

9.71

In [5]:
def scaling(data):
    # Drop the response variable class since we only need to scale numeric variables
    # Store the new dataset to a dataframe called df
    if 'Class' in data.columns:
        data_scale = data.drop('Class', 1)
    else:
        data_scale = data

    # Loop through each column and scale the values
    # write the scaled value back to df
    for col in list(data_scale.columns):
        data_scale[col] = (data_scale[[col]]-data_scale[[col]].min())/(data_scale[[col]].max()-data_scale[[col]].min())
  
    # print out the scaled dataset
    display(data_scale)
    return(data_scale)

# call the scaling function and add the class back to our dataset

In [6]:
data_scale = scaling(data)
data_scale["Class"] = data["Class"]
display(data_scale)

,F00,F01,F02,F03,F04,F05,F06,F07,F08,F09,...,F20,F21,F22,F23,F24,F25,F26,F27,F28,F29
0,0.521037,0.022658,0.545989,0.363733,0.593753,0.792037,0.703140,0.731113,0.686364,0.605518,...,0.620776,0.141525,0.668310,0.450698,0.601136,0.619292,0.568610,0.912027,0.598462,0.418864
1,0.643144,0.272574,0.615783,0.501591,0.289880,0.181768,0.203608,0.348757,0.379798,0.141323,...,0.606901,0.303571,0.539818,0.435214,0.347553,0.154563,0.192971,0.639175,0.233590,0.222878
2,0.601496,0.390260,0.595743,0.449417,0.514309,0.431017,0.462512,0.635686,0.509596,0.211247,...,0.556386,0.360075,0.508442,0.374508,0.483590,0.385375,0.359744,0.835052,0.403706,0.213433
3,0.210090,0.360839,0.233501,0.102906,0.811321,0.811361,0.565604,0.522863,0.776263,1.000000,...,0.248310,0.385928,0.241347,0.094008,0.915472,0.814012,0.548642,0.884880,1.000000,0.773711
4,0.629893,0.156578,0.630986,0.489290,0.430351,0.347893,0.463918,0.518390,0.378283,0.186816,...,0.519744,0.123934,0.506948,0.341575,0.437364,0.172415,0.319489,0.558419,0.157500,0.142595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,0.690000,0.428813,0.678668,0.566490,0.526948,0.296055,0.571462,0.690358,0.336364,0.132056,...,0.623266,0.383262,0.576174,0.452664,0.461137,0.178527,0.328035,0.761512,0.097575,0.105667
565,0.622320,0.626987,0.604036,0.474019,0.407782,0.257714,0.337395,0.486630,0.349495,0.113100,...,0.560655,0.699094,0.520892,0.379915,0.300007,0.159997,0.256789,0.559450,0.198502,0.074315
566,0.455251,0.621238,0.445788,0.303118,0.288165,0.254340,0.216753,0.263519,0.267677,0.137321,...,0.393099,0.589019,0.379949,0.230731,0.282177,0.273705,0.271805,0.487285,0.128721,0.151909
567,0.644564,0.663510,0.665538,0.475716,0.588336,0.790197,0.823336,0.755467,0.675253,0.425442,...,0.633582,0.730277,0.668310,0.402035,0.619626,0.815758,0.749760,0.910653,0.497142,0.452315
568,0.036869,0.501522,0.028540,0.015907,0.000000,0.074351,0.000000,0.000000,0.266162,0.187026,...,0.054287,0.489072,0.043578,0.020497,0.124084,0.036043,0.000000,0.000000,0.257441,0.100682

,F00,F01,F02,F03,F04,F05,F06,F07,F08,F09,...,F21,F22,F23,F24,F25,F26,F27,F28,F29,Class
0,0.521037,0.022658,0.545989,0.363733,0.593753,0.792037,0.703140,0.731113,0.686364,0.605518,...,0.141525,0.668310,0.450698,0.601136,0.619292,0.568610,0.912027,0.598462,0.418864,M
1,0.643144,0.272574,0.615783,0.501591,0.289880,0.181768,0.203608,0.348757,0.379798,0.141323,...,0.303571,0.539818,0.435214,0.347553,0.154563,0.192971,0.639175,0.233590,0.222878,M
2,0.601496,0.390260,0.595743,0.449417,0.514309,0.431017,0.462512,0.635686,0.509596,0.211247,...,0.360075,0.508442,0.374508,0.483590,0.385375,0.359744,0.835052,0.403706,0.213433,M
3,0.210090,0.360839,0.233501,0.102906,0.811321,0.811361,0.565604,0.522863,0.776263,1.000000,...,0.385928,0.241347,0.094008,0.915472,0.814012,0.548642,0.884880,1.000000,0.773711,M
4,0.629893,0.156578,0.630986,0.489290,0.430351,0.347893,0.463918,0.518390,0.378283,0.186816,...,0.123934,0.506948,0.341575,0.437364,0.172415,0.319489,0.558419,0.157500,0.142595,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,0.690000,0.428813,0.678668,0.566490,0.526948,0.296055,0.571462,0.690358,0.336364,0.132056,...,0.383262,0.576174,0.452664,0.461137,0.178527,0.328035,0.761512,0.097575,0.105667,M
565,0.622320,0.626987,0.604036,0.474019,0.407782,0.257714,0.337395,0.486630,0.349495,0.113100,...,0.699094,0.520892,0.379915,0.300007,0.159997,0.256789,0.559450,0.198502,0.074315,M
566,0.455251,0.621238,0.445788,0.303118,0.288165,0.254340,0.216753,0.263519,0.267677,0.137321,...,0.589019,0.379949,0.230731,0.282177,0.273705,0.271805,0.487285,0.128721,0.151909,M
567,0.644564,0.663510,0.665538,0.475716,0.588336,0.790197,0.823336,0.755467,0.675253,0.425442,...,0.730277,0.668310,0.402035,0.619626,0.815758,0.749760,0.910653,0.497142,0.452315,M
568,0.036869,0.501522,0.028540,0.015907,0.000000,0.074351,0.000000,0.000000,0.266162,0.187026,...,0.489072,0.043578,0.020497,0.124084,0.036043,0.000000,0.000000,0.257441,0.100682,B

In [7]:
mean_dic = {}
for col in list(data_scale.columns):
    if col!="Class":
        #print(col,np.mean(data_scale[col]))
        mean_dic[col] = np.mean(data_scale[col])

In [8]:
mean_dic

{'F00': 0.3382219574941815,
 'F01': 0.3239651168803228,
 'F02': 0.3329350659381915,
 'F03': 0.21692008640113902,
 'F04': 0.39478451922974755,
 'F05': 0.2606005281356261,
 'F06': 0.20805837820342832,
 'F07': 0.24313690790232234,
 'F08': 0.37960536826969166,
 'F09': 0.2703793142760695,
 'F10': 0.10634512266486168,
 'F11': 0.18932404240298506,
 'F12': 0.09937611208187036,
 'F13': 0.06263579446713657,
 'F14': 0.18111904376275845,
 'F15': 0.1744385108305818,
 'F16': 0.08053968773854543,
 'F17': 0.22345400800532397,
 'F18': 0.17814345091703052,
 'F19': 0.10019291165486299,
 'F20': 0.29666274659119135,
 'F21': 0.3639984861032524,
 'F22': 0.28313766947446856,
 'F23': 0.17090619551102404,
 'F24': 0.40413784603186037,
 'F25': 0.2202123234825811,
 'F26': 0.217402941936136,
 'F27': 0.3938358185518697,
 'F28': 0.26330686216736543,
 'F29': 0.18959607256459787}

In [9]:
data_scale['Class'].value_counts()["B"]

357

In [10]:
data_scale['Class'].value_counts()

B    357
M    212
Name: Class, dtype: int64

# The function for calculating entropy

In [11]:
def entropyCal(count1,count2):
    totalC = count1 + count2
    return -(count1/totalC)*np.log2(count1/totalC) -(count2/totalC)*np.log2(count2/totalC)

In [12]:
entropy_root = entropyCal(data_scale['Class'].value_counts()["B"],data_scale['Class'].value_counts()["M"])
entropy_root

0.9526351224018599

# The function for calculating gini

In [13]:
def giniCal(count1,count2):
    totalC = count1 + count2
    return 1-(pow((count1/totalC),2)+pow((count2/totalC),2))

In [14]:
gini_root = giniCal(data_scale['Class'].value_counts()["B"],data_scale['Class'].value_counts()["M"])
gini_root

0.4675300607546925

In [15]:
print("Class B observations:",data_scale['Class'].value_counts()["B"])
print("Class M observations:",data_scale['Class'].value_counts()["M"])
print("Total observations:",len(data_scale['Class']))
print("Root gini:",gini_root)
print("Root entropy",entropy_root)

Class B observations: 357
Class M observations: 212
Total observations: 569
Root gini: 0.4675300607546925
Root entropy 0.9526351224018599

In [16]:
for col in list(data_scale.columns):
    if col!="Class":
        child1_count = sum(data_scale[col] < mean_dic[col])
        child2_count = sum(data_scale[col] >= mean_dic[col])
        child_total = child1_count + child2_count
        
        child1_count_B = data_scale[data_scale[col] < mean_dic[col]]["Class"].value_counts()["B"]
        child1_count_M = data_scale[data_scale[col] < mean_dic[col]]["Class"].value_counts()["M"]
        
        gini_child1 = giniCal(child1_count_B,child1_count_M)
        entropy_child1 = entropyCal(child1_count_B,child1_count_M)
        
        child2_count_B = data_scale[data_scale[col] >= mean_dic[col]]["Class"].value_counts()["B"]
        child2_count_M = data_scale[data_scale[col] >= mean_dic[col]]["Class"].value_counts()["M"]
        
        gini_child2 = giniCal(child2_count_B,child2_count_M)
        entropy_child2 = entropyCal(child2_count_B,child2_count_M)
        
        gini_commbined = child1_count/child_total*gini_child1 + child2_count/child_total*gini_child2
        entropy_commbined = child1_count/child_total*entropy_child1 + child2_count/child_total*entropy_child2
        print(gini_commbined,entropy_commbined)

0.23076184675243638 0.5592118514490785
0.37196835026708386 0.8000519310764684
0.22077230795446284 0.5404436337587665
0.22515390247391048 0.5540872922302309
0.4266356496077186 0.8884139635199734
0.3160393727420153 0.7078657561423768
0.20118147452112187 0.5044005063979389
0.15650059801292926 0.41263751989490716
0.4359835061555076 0.9035700483420455
0.4675141654938051 0.95261058979152
0.29920069248095715 0.6857696935672699
0.4671370605063376 0.9520275745670783
0.29487620481107507 0.6784344847013235
0.2266966955658439 0.5549126621179664
0.46418535994390575 0.9474295469790142
0.4131745470658229 0.8689124297652342
0.3998932743264217 0.8482216290453077
0.3740462623604994 0.8048833301729776
0.46508227495782917 0.9488271261325443
0.45281735277122526 0.9301451079901202
0.16726872284333633 0.43996962965070563
0.3778355825517735 0.8093703583540102
0.14984868793545592 0.40340950938970344
0.14764125993972416 0.40000905790227587
0.40774399174927434 0.8580709603587651
0.3264353556706605 0.7287407756824476
0.24911548040843057 0.5897392823763041
0.18213364698968695 0.45627658432287266
0.41667206203728996 0.8734865889497556
0.4298534465670295 0.8947372291248281

In [44]:
sum(data_scale['F00']<mean_dic['F00'])

343

In [47]:
data_scale[data_scale['F00'] < mean_dic["F00"]]["Class"].value_counts()["B"]

311

Feature name
Feature mean value after scaling
Child 1 count for class "B"
Child 1 count for class "M"
Child 1 Gini
Child 1 Entropy
Child 2 count for class "B"
Child 2 count for class "M"
Child 2 Gini
Child 2 Entropy
Combined Gini for Child 1 and Child 2
Combined Entropy for Child 1 and Child 2

In [15]:
column_names = ["name","mean","child1B","child1M","child1gini","child1entropy",
                "child2B","child2M","child1gini","child1entropy","combinedgini","combinedentropy"]
df = pd.DataFrame(columns = column_names)
df

Empty DataFrame
Columns: [name, mean, child1B, child1M, child1gini, child1entropy, child2B, child2M, child1gini, child1entropy, combinedgini, combinedentropy]
Index: []